spring:
 data:
   mongodb:
     uri: mongodb://localhost:27017/social-user
     username: root
     password: password
    #generate-unique-name: false
server:
  port: 8083

user-service:
  url: http://user-service:8082


