spring:
 data:
   mongodb:
     authentication-database: admin
     database: social
     username: root
     password: password
     auto-index-creation: true
    #generate-unique-name: false
server:
  port: 8083

user-service:
  url: http://localhost:8082


