spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:./users
    username: sa
    #generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8082

user-service:
  url: http://localhost:8080
