spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:./users;AUTO_SERVER=TRUE
    username: sa
    #generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8083

user-service:
  url: http://localhost:8082
